{{- if .Values.monitoring.enabled }}
apiVersion: management.cattle.io/v3
kind: MultiClusterChart
metadata:
  name: monitoring-crd
spec:
  paused: {{ .Values.monitoring.paused }}
  chart: "rancher-monitoring-crd"
  repoName: "rancher-charts"
  releaseName: "rancher-monitoring-crd"
  version: {{ .Values.monitoring.version }}
  takeOwnership: {{ .Values.monitoring.takeOwnership }}
  timeoutSeconds: {{ .Values.monitoring.timeoutSeconds }}
  {{- if .Values.monitoring.values }}
  values: 
{{ toYaml .Values.monitoring.values | indent 4 }}
  {{- end }}
  {{- if .Values.monitoring.diff }}
  diff:
{{ toYaml .Values.monitoring.diff | indent 4 }}
  {{- end }}
  force: {{ .Values.monitoring.force }}
  maxHistory: {{ .Values.monitoring.maxHistory }}
  defaultNamespace: {{ .Values.monitoring.defaultNamespace }}
  namespace: {{ .Values.monitoring.targetNamespace }}
  serviceAccount: {{ .Values.monitoring.serviceAccount }}
  targets:
  - clusterName: {{ .Values.cluster.name }}
---
apiVersion: management.cattle.io/v3
kind: MultiClusterChart
metadata:
  name: monitoring
spec:
  paused: {{ .Values.monitoring.paused }}
  chart: "rancher-monitoring"
  repoName: "rancher-charts"
  releaseName: "rancher-monitoring"
  version: {{ .Values.monitoring.version }}
  takeOwnership: {{ .Values.monitoring.takeOwnership }}
  timeoutSeconds: {{ .Values.monitoring.timeoutSeconds }}
  {{- if .Values.monitoring.values }}
  values: 
{{ toYaml .Values.monitoring.values | indent 4 }}
  {{- end }}
  {{- if .Values.monitoring.diff }}
  diff:
{{ toYaml .Values.monitoring.diff | indent 4 }}
  {{- end }}
  force: {{ .Values.monitoring.force }}
  maxHistory: {{ .Values.monitoring.maxHistory }}
  defaultNamespace: {{ .Values.monitoring.defaultNamespace }}
  namespace: {{ .Values.monitoring.targetNamespace }}
  serviceAccount: {{ .Values.monitoring.serviceAccount }}
  targets:
  - clusterName: {{ .Values.cluster.name }}
---
{{- end }}

{{ range $index, $chart := .Values.charts }}
apiVersion: management.cattle.io/v3
kind: MultiClusterChart
metadata:
  name: {{ $chart.name }}
  namespace: {{ $chart.namespace }}
spec:
  paused: {{ $chart.paused }}
  chart: {{ $chart.chartName }}
  repoName: {{ $chart.repoName }}
  releaseName: {{ $chart.releaseName }}
  version: {{ $chart.version }}
  takeOwnership: {{ $chart.takeOwnership }}
  timeoutSeconds: {{ $chart.timeoutSeconds }}
  {{- if $chart.values }}
  values: 
{{ toYaml $chart.values | indent 4 }}
  {{- end }}
  {{- if $chart.diff }}
  diff:
{{ toYaml $chart.diff | indent 4 }}
  {{- end }}
  force: {{ $chart.force }}
  maxHistory: {{ $chart.maxHistory }}
  defaultNamespace: {{ $chart.defaultNamespace }}
  namespace: {{ $chart.targetNamespace }}
  serviceAccount: {{ $chart.serviceAccount }}
  targets:
  - clusterName: {{ $.Values.cluster.name }}
---
{{- end }}

